# Generated by Django 6.0.7 on 2026-07-19 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Turn on to reveal points to customers and start awarding them on completed orders.')),
                ('program_name', models.CharField(blank=True, default="Brew's Ko Rewards", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gamification Settings',
                'verbose_name_plural': 'Gamification Settings',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, default='Small-batch roasted, daily', max_length=150)),
                ('hero_title', models.CharField(blank=True, default='Brewed with Passion, Served with Comfort.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default="Discover handcrafted coffee and delightful treats at Brew's Ko.", max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('about_eyebrow', models.CharField(blank=True, default='Our Story', max_length=150)),
                ('about_title', models.CharField(blank=True, default='A cup made with intention, in a place made for pause.', max_length=255)),
                ('about_text_1', models.TextField(blank=True, default="Brew's Ko began as a small corner counter with one espresso machine and a big dream: to give our community a warm space to slow down.")),
                ('about_text_2', models.TextField(blank=True, default="We believe great coffee shouldn't be rushed — thoughtfully sourced beans, patiently brewed, served in a space that feels like a warm hug on a busy day.")),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('feature_1_icon', models.CharField(blank=True, default='bi-flower1', max_length=50)),
                ('feature_1_title', models.CharField(blank=True, default='Ethically Sourced', max_length=100)),
                ('feature_1_text', models.CharField(blank=True, default='Direct-trade beans from local farms', max_length=200)),
                ('feature_2_icon', models.CharField(blank=True, default='bi-house-heart', max_length=50)),
                ('feature_2_title', models.CharField(blank=True, default='Relaxing Atmosphere', max_length=100)),
                ('feature_2_text', models.CharField(blank=True, default='A cozy space to work, chat, or unwind', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_drink',
            field=models.BooleanField(default=True, help_text='Uncheck for non-drink categories (e.g. pastries) — controls whether size options are shown.'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(blank=True, help_text='Set automatically when a signed-in customer checks out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='dining_option',
            field=models.CharField(choices=[('for_here', 'For Here'), ('to_go', 'To Go')], default='to_go', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_awarded',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('large', 'Large')], help_text='Snapshot of the size ordered.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='e.g. Espresso, Steamed Milk, Vanilla Syrup. Shown on the product detail page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Gamification points a customer earns per unit ordered (admin-assigned).'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('regular', 'Regular'), ('large', 'Large')], default='regular', help_text='Applicable to drinks — shown on the menu and product page for drink categories.', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('product_added', 'Product added'), ('product_updated', 'Product updated'), ('category_added', 'Category added'), ('category_updated', 'Category updated'), ('order_received', 'Order received'), ('order_completed', 'Order completed'), ('order_updated', 'Order updated'), ('customer_joined', 'Customer joined')], max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('points', models.PositiveIntegerField(default=0, help_text='Gamification points balance.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='shop.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
    ]
