# Generated by Django 6.0.7 on 2026-07-19 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_gamificationsettings_homepagecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='cart_data',
            field=models.JSONField(blank=True, default=dict, help_text='Persisted cart contents — survives logout/login.'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars', validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.customerprofile')),
                ('product', models.ForeignKey(blank=True, help_text="Leave blank for a store-wide review of Brew's Ko itself.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
