# Generated by Django 6.0.7 on 2026-07-19 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customerprofile_cart_data_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Large size price. Required for drink categories — Regular and Large are both always offered.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Regular size price (or the only price, for non-drink items).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
