# Generated by Django 6.0.7 on 2026-07-23 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_size_product_price_large_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='years_roasting',
            field=models.PositiveIntegerField(default=10, help_text="Shown in the hero stats bar (e.g. '10+ Years Roasting'). Menu count and rating are computed automatically."),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('product_added', 'Product added'), ('product_updated', 'Product updated'), ('category_added', 'Category added'), ('category_updated', 'Category updated'), ('order_received', 'Order received'), ('order_completed', 'Order completed'), ('order_updated', 'Order updated'), ('customer_joined', 'Customer joined'), ('payment_received', 'Payment received')], max_length=30),
        ),
        migrations.CreateModel(
            name='CashierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashiers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='GCash transaction reference number (required for GCash payments).', max_length=50)),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
