# Generated by Django 6.0.7 on 2026-07-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_homepagecontent_years_roasting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoboothStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photobooth/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photobooth_strips', to='shop.customerprofile')),
            ],
            options={
                'verbose_name': 'Photobooth Strip',
                'verbose_name_plural': 'Photobooth Strips',
                'ordering': ['-created_at'],
            },
        ),
    ]
